/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reclame;

import java.io.File;
import java.io.FileFilter;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author crist
 */
public class Reclame extends javax.swing.JPanel implements Runnable {

    /**
     * Creates new form Reclame
     */
    public Reclame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rPoza = new javax.swing.JLabel();

        rPoza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rPoza.setMaximumSize(new java.awt.Dimension(100, 100));
        rPoza.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rPoza, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rPoza, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void run() {
        String u = this.getClass().getClassLoader().getResource("./reclame").getPath();
//   splash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartedetelefon/phone-book.jpg"))); // NOI18N
        File dir = new File(u);
        File[] poze = dir.listFiles();
        
        FileFilter filtruJPG = new FileFilter() {
            @Override
            public boolean accept(File file) {
                return file.getName().toLowerCase().endsWith(".jpg");
            }
        
        };
        
        poze = dir.listFiles(filtruJPG);
        
        if (poze.length == 0) {
         rPoza.setText("Zona pentru reclama!");
        }
        
        for(int i=1; i<poze.length; i++){
            if(Thread.interrupted()){
                return;
            }
            try {
                int random = (int )(3000 + Math.random() * 2000);
                Thread.sleep(random);
            } catch (InterruptedException ex) {
                return;
            }
//            System.out.println(poze[i]); 
            int random = (int )(Math.random() * poze.length);

            File cale = poze[random];
            rPoza.setIcon(new javax.swing.ImageIcon(cale.getAbsolutePath()));
              if (i == (poze.length - 1)) {
                  i = 0;
              }
         }
    }
//    public static void main(String[] args) {
//        new Thread(new Reclame()).start();
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel rPoza;
    // End of variables declaration//GEN-END:variables
}
